### POST request
POST http://localhost:4000/api/posts/ HTTP/1.1
content-type: application/json

{
   "title": "The Way of Kings",
   "author": "Brandon Sanderson",
   "description": "The Way of Kings is a world controlled by the Lord Ruler, a powerful and brutal being who has lived for 1,000 years.",
   "likes": 9,
   "comment": [{"blue": "good book!"}]
}

### GET request
GET http://localhost:4000/api/posts/ HTTP/1.1
content-type: application/json


### PUT/PATCH request
PUT http://localhost:4000/api/posts/65e6afb3f5160d4db945afc8 HTTP/1.1
content-type: application/json

{
   "title": "The Final Empire"
}

### DELETE request
DELETE http://localhost:4000/api/posts/65e6c02ffbaa945b0897a54e HTTP/1.1
content-type: application/json


### GET request
GET http://localhost:4000/api/users/ HTTP/1.1
content-type: application/json

### GET request
GET http://localhost:4000/api/tickets/ HTTP/1.1
content-type: application/json